name: Uptime of Containers on East US 2 EUAP

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  uptime-eastus2euap:
    uses: ./.github/workflows/uptime/uptime.yml
    secrets: inherit
    with:
      location: eastus2euap
