FROM mcr.microsoft.com/azureml/minimal-ubuntu20.04-py38-cpu-inference:20231102.v2

USER root
RUN apt update && apt upgrade -y && apt install -y python3-pip && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY key_release/payload.py /app/

RUN python -m pip install requests
CMD ["python", "payload.py"]