name: Status of West Europe (Large Containers)

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  simple-server-8gb:
    name: Simple Server 8GB
    uses: ./.github/workflows/test/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '["westeurope"]'
      manifest-modifiers: "SIMPLE_SERVER_CORES=4;SIMPLE_SERVER_RAM=8"

  simple-server-16gb:
    name: Simple Server 16GB
    uses: ./.github/workflows/test/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '["westeurope"]'
      manifest-modifiers: "SIMPLE_SERVER_CORES=4;SIMPLE_SERVER_RAM=16"