# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attestation_sidecar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61ttestation_sidecar.proto\x12\x15\x61ttestation_container\".\n\x17\x46\x65tchAttestationRequest\x12\x13\n\x0breport_data\x18\x01 \x01(\x0c\"e\n\x15\x46\x65tchAttestationReply\x12\x13\n\x0b\x61ttestation\x18\x01 \x01(\x0c\x12\x1d\n\x15platform_certificates\x18\x02 \x01(\x0c\x12\x18\n\x10uvm_endorsements\x18\x03 \x01(\x0c\x32\x8a\x01\n\x14\x41ttestationContainer\x12r\n\x10\x46\x65tchAttestation\x12..attestation_container.FetchAttestationRequest\x1a,.attestation_container.FetchAttestationReply\"\x00\x42NZLgithub.com/Microsoft/confidential-aci-examples/examples/attestation/protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attestation_sidecar_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZLgithub.com/Microsoft/confidential-aci-examples/examples/attestation/protobuf'
  _globals['_FETCHATTESTATIONREQUEST']._serialized_start=52
  _globals['_FETCHATTESTATIONREQUEST']._serialized_end=98
  _globals['_FETCHATTESTATIONREPLY']._serialized_start=100
  _globals['_FETCHATTESTATIONREPLY']._serialized_end=201
  _globals['_ATTESTATIONCONTAINER']._serialized_start=204
  _globals['_ATTESTATIONCONTAINER']._serialized_end=342
# @@protoc_insertion_point(module_scope)
