FROM python:latest
WORKDIR /app
COPY attestation/protobuf protobuf
COPY attestation/get_attestation.py get_attestation.py
COPY attestation/payload.py payload.py
RUN pip install protobuf grpcio grpcio-tools
CMD ["python", "payload.py"]
