FROM mcr.microsoft.com/cbl-mariner/base/python:3.9
WORKDIR /app
COPY attestation/protobuf protobuf
COPY attestation/get_attestation.py get_attestation.py
COPY attestation/payload.py payload.py
RUN pip install protobuf grpcio grpcio-tools
RUN alias python=python3
CMD ["python", "payload.py"]
