version: '3'
services:
  primary:
    image: $REGISTRY/sidecar/primary:${TAG:-latest}
    network_mode: "host"
    depends_on:
      - sidecar
    build:
      context: .
      dockerfile: primary.Dockerfile
  sidecar:
    image: $REGISTRY/sidecar/sidecar:${TAG:-latest}
    network_mode: "host"
    build:
      context: .
      dockerfile: sidecar.Dockerfile
