name: Build and Push Container Image

on:
  workflow_call:
    inputs:
      dockerfile:
        description: "Dockerfile to build and push"
        required: true
        type: string
      tag:
        description: "Tag to build and push"
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZ_REGISTRY_LOGIN }}
          username: ${{ secrets.AZ_REGISTRY_USERNAME }}
          password: ${{ secrets.AZ_REGISTRY_PASSWORD }}

      - name: Get Dockerfile Context
        run: |
          echo DOCKERFILE_CONTEXT=$(dirname ${{ inputs.dockerfile }}) >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        env:
          DOCKERFILE_CONTEXT: ${{ env.DOCKERFILE_CONTEXT }}
        with:
          context: ${{ env.DOCKERFILE_CONTEXT }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: |
            ${{ inputs.tag }}
