name: Deploy Container

on:
  workflow_call:
    inputs:
      arm-template:
        description: "ARM Template to deploy"
        required: true
        type: string
      deployment-name:
        description: "Name of the deployment"
        required: true
        type: string

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download ARM Template Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.arm-template }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Log into Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.SP_APP_ID }} \
            --password ${{ secrets.SP_PASSWORD }} \
            --tenant ${{ secrets.SP_TENANT }}

      - name: Deploy Container on ACI
        run: |
          python infra/deploy_container.py \
            --subscription-id ${{ secrets.AZ_SUBSCRIPTION_ID }} \
            --arm-template-path arm_template.json \
            --resource-group ${{ secrets.AZ_RESOURCE_GROUP }} \
            --deployment-name ${{ inputs.deployment-name }} \
