name: _Deploy and Run Test

on:
  workflow_call:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: string
      location:
        description: "Location to deploy ACI to"
        required: true
        type: string
      image:
        description: "Image to deploy to ACI"
        required: true
        type: string
      security-policy-artifact-name:
        description: "Security policy artifact name containing all policies"
        required: true
        type: string
      security-policy:
        description: "Security Policy to use for ACI"
        required: true
        type: string

jobs:
  generate-arm-template:
    name: " "
    uses: ./.github/workflows/_generate_arm_template.yml
    secrets: inherit
    with:
      label: ${{ inputs.location }}/${{ inputs.security-policy }}
      container-group-name: ${{ inputs.test }}-${{ inputs.location }}-${{ inputs.security-policy }}-${{ github.run_id }}-${{ github.run_attempt }}
      location: ${{ inputs.location }}
      image: ${{ inputs.image }}
      security-policy-artifact-name: ${{ inputs.security-policy-artifact-name }}
      security-policy: ${{ inputs.security-policy }}
      artifact-name: ${{ inputs.test }}-${{ inputs.location }}-${{ inputs.security-policy }}-${{ github.run_id }}-${{ github.run_attempt }}_arm_template

  deploy-container:
    name: " "
    uses: ./.github/workflows/_deploy_container.yml
    secrets: inherit
    needs: generate-arm-template
    with:
      label: ${{ inputs.location }}/${{ inputs.security-policy }}
      arm-template: ${{ inputs.test }}-${{ inputs.location }}-${{ inputs.security-policy }}-${{ github.run_id }}-${{ github.run_attempt }}_arm_template
      deployment-name: ${{ inputs.test }}-${{ inputs.location }}-${{ inputs.security-policy }}-${{ github.run_id }}-${{ github.run_attempt }}-deployment

  client-side-test:
    name: " "
    uses: ./.github/workflows/_client_side_test.yml
    secrets: inherit
    needs: deploy-container
    with:
      label: ${{ inputs.location }}/${{ inputs.security-policy }}
      test: ${{ inputs.test }}
      deployment-name: ${{ inputs.test }}-${{ inputs.location }}-${{ inputs.security-policy }}-${{ github.run_id }}-${{ github.run_attempt }}-deployment

  remove-container:
    name: " "
    uses: ./.github/workflows/_remove_container.yml
    secrets: inherit
    needs: client-side-test
    if: always()
    with:
      label: ${{ inputs.location }}/${{ inputs.security-policy }}
      deployment-name: ${{ inputs.test }}-${{ inputs.location }}-${{ inputs.security-policy }}-${{ github.run_id }}-${{ github.run_attempt }}-deployment
