name: Generate ARM Template

on:
  workflow_call:
    inputs:
      container-group-name:
        description: "Name of the container group to deploy"
        required: true
        type: string
      location:
        description: "Location to deploy ACI to"
        required: true
        type: string
      image:
        description: "Image to deploy to ACI"
        required: true
        type: string
      security-policy-artifact-name:
        description: "Security policy artifact name containing all policies"
        required: true
        type: string
      security-policy:
        description: "Security policy within the artifact to use for ACI"
        required: true
        type: string
      artifact-name:
        description: "Name of the generated template artifact"
        required: true
        type: string

jobs:
  generate-arm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Security Policy Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.security-policy-artifact-name }}
          path: security_policies

      - name: Print Security Policy
        run: cat security_policies/${{ inputs.security-policy }}

      - name: Generate ARM Template
        id: generate-arm-template
        run: |
          python infra/generate_arm_template.py \
            --container-group-name ${{ inputs.container-group-name }} \
            --location ${{ inputs.location }} \
            --image ${{ inputs.image }} \
            --security-policy "$(cat security_policies/${{ inputs.security-policy }} | base64)" \
            --registry-password ${{ secrets.AZ_REGISTRY_PASSWORD }} \
            --out arm_template.json

      - name: Print ARM Template
        run: cat arm_template.json

      - name: Upload ARM Template Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
          path: arm_template.json
