name: Resolve Manifest Variables

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      manifest:
        required: true
        type: string
        description: The Path to the Manifest File
      modifiers:
        type: string
        required: false
        default: ""
        description: Semi colon separated key value pairs of environment variables to override
    outputs:
      manifest:
        description: The manifest whith values resolved
        value: ${{ jobs.resolve-manifest-variables.outputs.manifest }}

jobs:
  resolve-manifest-variables:
    name: Resolve Manifest Variables
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.resolve.outputs.manifest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import GPG Key
        run: |
          echo -e "${{ secrets.ENCRYPTION_KEY }}" | gpg --import

      - name: Resolve Manifest Variables
        id: resolve
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_HSM_NAME: ${{ secrets.AZURE_HSM_NAME }}
          AZURE_HSM_ENDPOINT: ${{ secrets.AZURE_HSM_ENDPOINT }}
          AZURE_ATTESTATION_ENDPOINT: ${{ secrets.AZURE_ATTESTATION_ENDPOINT }}
          KEY_RELEASE_IMAGE: ${{ secrets.KEY_RELEASE_IMAGE }}
          ENCRYPTED_FILESYSTEM_IMAGE: ${{ secrets.ENCRYPTED_FILESYSTEM_IMAGE }}
          ATTESTATION_SIDECAR_IMAGE: ${{ secrets.ATTESTATION_SIDECAR_IMAGE }}
          SIDECARS_REGISTRY_URL: ${{ secrets.SIDECARS_REGISTRY_URL }}
          SIDECARS_REGISTRY_USERNAME: ${{ secrets.SIDECARS_REGISTRY_USERNAME }}
          SIDECARS_REGISTRY_PASSWORD: ${{ secrets.SIDECARS_REGISTRY_PASSWORD }}
          AZURE_REGISTRY_URL: ${{ secrets.AZURE_REGISTRY_URL }}
          AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
          AZURE_STORAGE_CONTAINER_URL: ${{ secrets.AZURE_STORAGE_CONTAINER_URL }}
          SIMPLE_SERVER_CORES: "1"
          SIMPLE_SERVER_RAM: "4"
        run: |
          IFS=";" read -ra modifiers <<< "${{ inputs.modifiers }}"
          for modifier in "${modifiers[@]}"; do
            IFS="=" read -ra key_value <<< "$modifier"
            if [[ "${key_value[0]}" == *"IMAGE"* ]]; then
              if [[ "${key_value[1]}" != "http://mcr.microsoft.com/"* && "${key_value[1]}" != "http://confidentialsidecars.azurecr.io/"* ]]; then
                echo "Untrusted image repository ${key_value[1]}, exiting"
                exit 1
              fi
            fi
            export "${key_value[0]}"="${key_value[1]}"
          done
          echo "manifest=$(python infra/resolve_manifest_variables.py ${{ inputs.manifest }} | \
            gpg -aeq --trust-mode always -r "Github Actions <\" \">" | \
            sed ':a;N;$!ba;s/\n/\\n/g')" >> $GITHUB_OUTPUT
