name: Resolve Manifest Variables

on:
  workflow_call:
    inputs:
      manifest:
        required: true
        type: string
        description: The Path to the Manifest File
    outputs:
      manifest:
        description: The manifest whith values resolved
        value: ${{ jobs.resolve-manifest-variables.outputs.manifest }}
        
jobs:
  
  resolve-manifest-variables:
    name: Resolve Manifest Variables
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.resolve.outputs.manifest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Resolve Manifest Variables
        id: resolve
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_HSM_NAME: ${{ secrets.AZURE_HSM_NAME }}
          AZURE_HSM_ENDPOINT: ${{ secrets.AZURE_HSM_ENDPOINT }}
          AZURE_ATTESTATION_ENDPOINT: ${{ secrets.AZURE_ATTESTATION_ENDPOINT }}
          KEY_RELEASE_IMAGE: ${{ secrets.KEY_RELEASE_IMAGE }}
          ENCRYPTED_FILESYSTEM_IMAGE: ${{ secrets.ENCRYPTED_FILESYSTEM_IMAGE }}
          ATTESTATION_SIDECAR_IMAGE: ${{ secrets.ATTESTATION_SIDECAR_IMAGE }}
          SIDECARS_REGISTRY_URL: ${{ secrets.SIDECARS_REGISTRY_URL }}
          SIDECARS_REGISTRY_USERNAME: ${{ secrets.SIDECARS_REGISTRY_USERNAME }}
          SIDECARS_REGISTRY_PASSWORD: ${{ secrets.SIDECARS_REGISTRY_PASSWORD }}
          AZURE_REGISTRY_URL: ${{ secrets.AZURE_REGISTRY_URL }}
          AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
          AZURE_STORAGE_CONTAINER_URL: ${{ secrets.AZURE_STORAGE_CONTAINER_URL }}
        run: |
          echo "${{ secrets.ENCRYPTION_KEY }}" | gpg --import public.key
          echo "manifest=$(python infra/resolve_manifest_variables.py ${{ inputs.manifest }} | sed 's/"/\\"/g' | gpg --armor --encyrpt -r "Github Actions")" >> $GITHUB_OUTPUT
          
      - name: Print Manifest
        run: |
          echo ${{ steps.resolve.outputs.manifest}}
          
  print-manifest:
    needs: resolve-manifest-variables
    name: Print Manifest
    runs-on: ubuntu-latest
    steps:
      - name: Print Manifest
        run: |
          echo ${{ needs.resolve-manifest-variables.outputs.manifest }}
          