name: Run Test

on:
  workflow_call:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: string

jobs:
  get-dash-case:
    runs-on: ubuntu-latest
    outputs:
      dashcase: ${{ steps.convert.outputs.dashcase }}
    steps:
      - name: Convert Test Name to Dash Case
        id: convert
        run: |
          echo dashcase="$(echo ${{ inputs.test }} | sed 's/_/-/g')"
          echo "dashcase="$(echo ${{ inputs.test }} | sed 's/_/-/g')" >> $GITHUB_OUTPUT"

  build-and-push-image:
    uses: ./.github/workflows/_build_and_push_image.yml
    secrets: inherit
    with:
      dockerfile: tests/${{ inputs.test }}/Dockerfile
      tag: ${{ vars.REGISTRY }}/${{ inputs.test }}:latest

  deploy-and-run-test:
    uses: ./.github/workflows/deploy_and_run.yml
    needs: [build-and-push-image, get-dash-case]
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        location: [eastus2euap, westeurope]
    with:
      test: ${{ inputs.test }}
      dash-case: "simple-server"
      location: ${{ matrix.location }}
      image: ${{ vars.REGISTRY }}/${{ inputs.test }}:latest
