name: Run Test

on:
  workflow_call:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: string

jobs:
  get-dash-case:
    runs-on: ubuntu-latest
    outputs:
      dashcase: ${{ steps.convert.outputs.dashcase }}
    steps:
      - name: Convert Test Name to Dash Case
        id: convert
        run: |
          echo "::set-output name=dashcase::$(echo ${{ inputs.test }} | sed 's/_/-/g')"

  build-and-push-image:
    uses: ./.github/workflows/_build_and_push_image.yml
    secrets: inherit
    with:
      dockerfile: tests/${{ inputs.test }}/Dockerfile
      tag: ${{ vars.REGISTRY }}/${{ inputs.test }}:latest

  generate-security-policy:
    uses: ./.github/workflows/_generate_security_policy.yml
    secrets: inherit
    with:
      image: ${{ vars.REGISTRY }}/${{ inputs.test }}:latest
      test: ${{ inputs.test }}
      artifact-name: ${{ inputs.test }}_security_policies

  deploy-and-run-test:
    uses: ./.github/workflows/_deploy_and_run.yml
    needs: [build-and-push-image, generate-security-policy, get-dash-case]
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        location: [eastus2euap, westeurope]
        security-policy: ["_generated.rego", "allow_all.rego"]
    with:
      test: ${{ inputs.test }}
      dash-case: "${{ needs.get-dash-case.outputs.dashcase }}"
      location: ${{ matrix.location }}
      image: ${{ vars.REGISTRY }}/${{ inputs.test }}:latest
      security-policy-artifact-name: ${{ inputs.test }}_security_policies
      security-policy: ${{ matrix.security-policy }}
