name: Per Test Workflow

on:
  workflow_call:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: string

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build_and_push_image.yml
    secrets: inherit
    with:
      dockerfile: tests/${{ inputs.test }}/Dockerfile
      tag: ${{ secrets.AZ_REGISTRY_LOGIN }}/${{ inputs.test }}:latest

  deploy-and-run-test:
    uses: ./.github/workflows/deploy_and_run.yml
    needs: build-and-push-image
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        location: [eastus2euap, westeurope]
    with:
      test: ${{ inputs.test }}
      location: ${{ matrix.location }}
