name: Build and Push Container Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [simple_server]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZ_REGISTRY_LOGIN }}
          username: ${{ secrets.AZ_REGISTRY_USERNAME }}
          password: ${{ secrets.AZ_REGISTRY_PASSWORD }}

      - name: Sanitise Test Name
        run: |
          DASH_CASE_TEST=$(echo ${{ matrix.test }} | sed 's/_/-/g')
          echo "DASH_TEST_CASE=$DASH_CASE_TEST" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: tests/${{ matrix.test }}
          file: tests/${{ matrix.test }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.AZ_REGISTRY_LOGIN }}/${{ env.DASH_CASE_TEST }}:latest
