name: Build and Push Container Images

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to build and push images for"
        required: true
        type: choice
        options:
          - simple_server
  workflow_call:
    inputs:
      test:
        description: "Test to build and push images for"
        required: true
        type: string

jobs:

  get-images-to-build:
    name: Get Images to Build
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.get-images-to-build.outputs.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Images to Build
        id: get-images-to-build
        run: echo "::set-output name=images::$(python infra/read_manifest_images.py tests/${{ inputs.test }}/manifest.json)"

  build-and-push-image:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs: get-images-to-build
    strategy:
      matrix:
        images: ${{ fromJson(needs.get-images-to-build.outputs.images) }}
    steps:
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZ_REGISTRY_LOGIN }}
          username: ${{ secrets.AZ_REGISTRY_USERNAME }}
          password: ${{ secrets.AZ_REGISTRY_PASSWORD }}

      - name: Get Docker Info
        id: docker-info
        run: |
          echo "::set-output name=repository::$(echo ${{ matrix.images }} | cut -d':' -f1 )"
          echo "::set-output name=file::$(echo ${{ matrix.images }} | cut -d':' -f2 )"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        env:
          DOCKERFILE_CONTEXT: tests/${{ inputs.test }}
        with:
          context: tests/${{ inputs.test }}
          file: tests/${{ inputs.test }}/${{ steps.docker-info.outputs.file }}
          push: true
          tags: |
            ${{ vars.REGISTRY }}/${{ inputs.test }}/${{ steps.docker-info.outputs.repository }}:${{ github.sha }}
