name: Build and Push Container Image

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to build the image for"
        required: true
        type: choice
        options: ["simple_server"]
  workflow_call:
    inputs:
      test:
        description: "Test to build the container image for"
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZ_REGISTRY_LOGIN }}
          username: ${{ secrets.AZ_REGISTRY_USERNAME }}
          password: ${{ secrets.AZ_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: tests/${{ github.event.inputs.test }}
          file: tests/${{ github.event.inputs.test }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.AZ_REGISTRY_LOGIN }}/${{ github.event.inputs.test }}:latest
