name: Cleanup Storage Account

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup-hsm:
    name: Cleanup Storage Account Blobs
    runs-on: ubuntu-latest
    steps:
      - name: Log into Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_SERVICE_PRINCIPAL_APP_ID }} \
            --password ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} \
            --tenant ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}

      - name: Get Connection String
        run: |
          CONNECTION_STRING=$(az storage account show-connection-string \
            --name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --query connectionString \
            --output tsv)
          echo "CONNECTION_STRING=$CONNECTION_STRING" >> $GITHUB_ENV

      - name: Delete Blobs
        run: |
          echo $CONNECTION_STRING
          az storage blob delete-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --source ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} --connection-string $CONNECTION_STRING
