name: Cleanup Storage Account

on:
  workflow_call: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup-hsm:
    name: Cleanup Storage Account Blobs
    runs-on: ubuntu-latest
    steps:
      - name: Log into Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_SERVICE_PRINCIPAL_APP_ID }} \
            --password ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} \
            --tenant ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}

      - name: Delete Blobs
        run: az storage blob list --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --container-name ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} --query "[].name" -o tsv | xargs -I{} az storage blob delete --container-name ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} --name {} --auth-mode login
