name: Cleanup Registry

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  cleanup_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Log into Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_SERVICE_PRINCIPAL_APP_ID }} \
            --password ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} \
            --tenant ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_URL }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Cleanup Registry
        run: |
          # The filter looks for at least one digit as a proxy for auto
          # generated tags
          az acr run \
            --cmd "acr purge --filter '.*:.*\d+.*' --ago 1d" \
            --registry ${{ secrets.AZURE_REGISTRY_URL }} \
            /dev/null
