name: Cleanup HSM

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup-hsm:
    name: Cleanup HSM Keys
    runs-on: ubuntu-latest
    steps:
      - name: Log into Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_SERVICE_PRINCIPAL_APP_ID }} \
            --password ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} \
            --tenant ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}

      - name: Delete HSM Keys
        run: az keyvault key list --hsm-name ${{ secrets.AZURE_HSM_NAME }} --query "[].kid" -o tsv | xargs -I{} az keyvault key delete --id {}
