name: Cleanup Azure Resources

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup-running-acis:
    name: Cleanup Running Container Groups
    runs-on: ubuntu-latest
    environment: CI
    steps:

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Delete All Container Groups
        run: |
          RUNNING_CONTAINERS=$(az container list \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

          for container in $(echo $RUNNING_CONTAINERS | jq -r '.[].id'); do
              echo "Deleting container group: ${container}"
              az resource delete --ids ${container}
          done

  cleanup_registry:
    name: Cleanup Container Registry
    runs-on: ubuntu-latest
    environment: CI
    steps:

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ secrets.AZURE_REGISTRY_USERNAME }}

      - name: Cleanup Registry
        run: |
          # The filter looks for at least one digit as a proxy for auto
          # generated tags
          az acr run \
            --cmd "acr purge --filter '.*:.*\d+.*' --ago 1d" \
            --registry ${{ secrets.AZURE_REGISTRY_URL }} \
            /dev/null
