name: Cleanup ACI

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs:
    cleanup:
        runs-on: ubuntu-latest
        steps:

            - name: Log into Azure
              run: |
                  az login --service-principal \
                  --username ${{ secrets.SP_APP_ID }} \
                  --password ${{ secrets.SP_PASSWORD }} \
                  --tenant ${{ secrets.SP_TENANT }}

            - name: Delete Failed Deployments
              run: |
                NON_RUNNING_CONTAINERS=$(az container list \
                    --resource-group c-aci-examples \
                    --query "[?provisioningState=='Failed' || provisioningState=='Unhealthy']")

                for container in $(echo $NON_RUNNING_CONTAINERS | jq -r '.[].id'); do
                    echo "Deleting container group: ${container}"
                    az resource delete --ids ${container}
                done

