name: Remove Container

on:
  workflow_dispatch:
    inputs:
      id:
        description: "Unique Identifier for this run"
        required: true
        type: string
      test:
        description: "Test to remove the ACI for"
        required: true
        type: choice
        options:
          - simple_server
      location:
        description: "Location to deploy ACI to"
        required: true
        type: string
      security-policy:
        description: "Security policy within the artifact to use for ACI"
        required: true
        type: string
  workflow_call:
    inputs:
      id:
        description: "Unique Identifier for this run"
        required: true
        type: string
      test:
        description: "Test to remove the ACI for"
        required: true
        type: string
      location:
        description: "Location to deploy ACI to"
        required: true
        type: string
      security-policy:
        description: "Security policy within the artifact to use for ACI"
        required: true
        type: string

jobs:
  remove-container:
    name: Remove Container (${{ inputs.location }}/${{ inputs.security-policy }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Matrix Cell Name
        id: generate-name
        run: echo "name=$(echo ${{ inputs.test }}-${{ inputs.location }}-${{ inputs.security-policy }}-${{ inputs.id }} | md5sum | sed 's/ //g' | sed 's/-//g')" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Log into Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_SERVICE_PRINCIPAL_APP_ID }} \
            --password ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} \
            --tenant ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}

      - name: Download ARM Template Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.generate-name.outputs.name }}_arm_template

      - name: Remove Container on ACI
        run: |
          python infra/delete_deployment.py \
            --subscription-id ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --deployment-name ${{ steps.generate-name.outputs.name }}-deployment \
            --arm-template-path arm_template.json
