on:
  workflow_dispatch:
    inputs:
      test-name:
        type: string
        required: true
      locations:
        type: string
        required: false
        default: '["westeurope"]'
      debug:
        type: boolean
        required: false
        default: false
      env:
        type: string
        required: false
        default: ""
  workflow_call:
    inputs:
      test-name:
        type: string
        required: true
      locations:
        type: string
        required: false
        default: '["westeurope"]'
      debug:
        type: boolean
        required: false
        default: false
      env:
        type: string
        required: false
        default: ""

jobs:
  generate-uid:
    name: Generate Unique ID
    runs-on: ubuntu-latest
    outputs:
      uid: ${{ steps.workflow-id.outputs.workflow-id }}
    steps:
      - name: Generate Unique ID
        id: workflow-id
        run: echo "workflow-id=$(openssl rand -hex 8 | tr -d '\n')" >> $GITHUB_OUTPUT

  resolve-manifest:
    name: Resolve Manifest Variables
    uses: ./.github/workflows/_resolve_manifest.yml
    secrets: inherit
    with:
      manifest: examples/${{ inputs.test-name }}/manifest.json
      modifiers: ${{ inputs.env }}

  push-example-images:
    name: Push Images
    uses: ./.github/workflows/_push_example_images.yml
    needs: [generate-uid, resolve-manifest]
    secrets: inherit
    with:
      tag: ${{ needs.generate-uid.outputs.uid }}
      manifest: ${{ needs.resolve-manifest.outputs.manifest }}

  generate-arm-templates:
    name: Generate ARM Templates
    uses: ./.github/workflows/_generate_arm_templates.yml
    needs: [generate-uid, resolve-manifest]
    secrets: inherit
    with:
      manifest: ${{ needs.resolve-manifest.outputs.manifest }}
      locations: ${{ inputs.locations }}
      image-tag: ${{ needs.generate-uid.outputs.uid }}

  test-generate:
    runs-on: ubuntu-latest
    needs: generate-arm-templates
    steps:
      - name: Decrypt ARM Templates
        run: |
          echo -e "${{ secrets.DECRYPTION_KEY }}" | gpg --import
          for template in ${{ toJson(needs.generate-arm-templates.outputs.arm-templates) }}; do
            echo -e $template | gpg --decrypt
          done
