name: Deploy Container

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to deploy a container for"
        required: true
        type: choice
        options: ["simple_server"]
  workflow_call:
    inputs:
      test:
        description: "Test to deploy a container for"
        required: true
        type: string

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download ARM Template Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.test }}_arm_template

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Log into Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.SP_APP_ID }} \
            --password ${{ secrets.SP_PASSWORD }} \
            --tenant ${{ secrets.SP_TENANT }}

      - name: Deploy Container on ACI
        run: |
          python infra/deploy_container.py \
            --subscription-id ${{ secrets.AZ_SUBSCRIPTION_ID }} \
            --arm-template-path ${{ inputs.test }}_arm_template.json \
            --resource-group ${{ secrets.AZ_RESOURCE_GROUP }} \
            --container-name ${{ inputs.test }}
