name: Deploy Container

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to deploy ACI for"
        required: true
        type: choice
        options:
          - simple_server
      location:
        description: "Location to deploy to"
        required: true
        type: string
      security-policy:
        description: "Security policy to use for ACI"
        required: true
        type: string
  workflow_call:
    inputs:
      test:
        description: "Test to deploy ACI for"
        required: true
        type: string
      location:
        description: "Location to deploy to"
        required: true
        type: string
      security-policy:
        description: "Security policy to use for ACI"
        required: true
        type: string

jobs:
  deploy-container:
    name: Deploy Container (${{ inputs.location }}/${{ inputs.security-policy }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Matrix Cell Name
        id: generate-name
        run: echo "::set-output name=name::$(echo ${{ inputs.test }}-${{ inputs.location }}-${{ inputs.security-policy }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job }} | md5sum | sed 's/ //g' | sed 's/-//g')"

      - name: Download ARM Template Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ steps.generate-name.outputs.name }}_arm_template

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Log into Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.SP_APP_ID }} \
            --password ${{ secrets.SP_PASSWORD }} \
            --tenant ${{ secrets.SP_TENANT }}

      - name: Deploy Container on ACI
        run: |
          python infra/deploy_container.py \
            --subscription-id ${{ secrets.AZ_SUBSCRIPTION_ID }} \
            --arm-template-path arm_template.json \
            --resource-group ${{ secrets.AZ_RESOURCE_GROUP }} \
            --deployment-name deployment-${{ steps.generate-name.outputs.name }} \
