name: Deploy Container

on:
  workflow_dispatch:
    inputs:
      id:
        description: "Unique Identifier for this run"
        required: true
        type: string
      test:
        description: "Test to deploy ACI for"
        required: true
        type: choice
        options:
          - simple_server
      location:
        description: "Location to deploy to"
        required: true
        type: string
      security-policy:
        description: "Security policy to use for ACI"
        required: true
        type: string
  workflow_call:
    inputs:
      id:
        description: "Unique Identifier for this run"
        required: true
        type: string
      test:
        description: "Test to deploy ACI for"
        required: true
        type: string
      location:
        description: "Location to deploy to"
        required: true
        type: string
      security-policy:
        description: "Security policy to use for ACI"
        required: true
        type: string

jobs:
  deploy-container:
    name: Deploy Container (${{ inputs.location }}/${{ inputs.security-policy }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Matrix Cell Name
        id: generate-name
        run: echo "name=$(echo ${{ inputs.test }}-${{ inputs.location }}-${{ inputs.security-policy }}-${{ inputs.id }} | md5sum | sed 's/ //g' | sed 's/-//g')" >> $GITHUB_OUTPUT

      - name: Download ARM Template Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.generate-name.outputs.name }}_arm_template

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Log into Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.SP_APP_ID }} \
            --password ${{ secrets.SP_PASSWORD }} \
            --tenant ${{ secrets.SP_TENANT }}

      - name: Deploy Container on ACI
        run: |
          python infra/deploy_container.py \
            --subscription-id ${{ secrets.AZ_SUBSCRIPTION_ID }} \
            --arm-template-path arm_template.json \
            --resource-group ${{ secrets.AZ_RESOURCE_GROUP }} \
            --deployment-name deployment-${{ steps.generate-name.outputs.name }} \

      - name: Check Container is Running
        run: |
          sleep 10 # Give the container a chance to stabilise
          CONTAINER_STATE=$(az container show \
              --name $(cat arm_template.json | jq -r '.resources[0].name') \
              --resource-group ${{ secrets.AZ_RESOURCE_GROUP }} \
            )
          echo $CONTAINER_STATE | jq
          [[ $(echo $CONTAINER_STATE | jq -r '.instanceView.state') == "Running" ]] && exit 0 || exit 1
