name: Deploy Container

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to deploy a container for"
        required: true
        type: choice
        options: ["simple_server"]

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r infra/requirements.txt

      - name: Log into Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.SP_APP_ID }} \
            --password ${{ secrets.SP_PASSWORD }} \
            --tenant ${{ secrets.SP_TENANT }}

      - name: Deploy Container with ACI
        run: |
          python infra/containers.py deploy \
            --subscription-id ${{ secrets.AZ_SUBSCRIPTION_ID }} \
            --resource-group ${{ secrets.AZ_RESOURCE_GROUP }} \
            --name ${{ github.event.inputs.test }} \
            --image ${{ secrets.AZ_REGISTRY_LOGIN }}/${{ github.event.inputs.test }}:latest \
            --registry-password ${{ secrets.AZ_REGISTRY_PASSWORD }}
