on:
  workflow_dispatch:
    inputs:
      test-name:
        type: string
        required: true
      locations:
        type: string
        required: false
        default: '["westeurope"]'
      debug:
        type: boolean
        required: false
        default: false
      env:
        type: string
        required: false
        default: ""
  workflow_call:
    inputs:
      test-name:
        type: string
        required: true
      locations:
        type: string
        required: false
        default: '["westeurope"]'
      debug:
        type: boolean
        required: false
        default: false
      env:
        type: string
        required: false
        default: ""

jobs:
  generate-uid:
    name: Generate Unique ID
    runs-on: ubuntu-latest
    outputs:
      uid: ${{ steps.workflow-id.outputs.workflow-id }}
    steps:
      - name: Generate Unique ID
        id: workflow-id
        run: echo "workflow-id=$(openssl rand -hex 8 | tr -d '\n')" >> $GITHUB_OUTPUT

  resolve-manifest:
    name: Resolve Manifest Variables
    uses: ./.github/workflows/_resolve_manifest.yml
    secrets: inherit
    with:
      manifest: examples/${{ inputs.test-name }}/manifest.json
      modifiers: ${{ inputs.env }}

  push-example-images:
    name: Push Images
    uses: ./.github/workflows/_push_example_images.yml
    needs: [generate-uid, resolve-manifest]
    secrets: inherit
    with:
      tag: ${{ needs.generate-uid.outputs.uid }}
      manifest: ${{ needs.resolve-manifest.outputs.manifest }}

  test-push:
    runs-on: ubuntu-latest
    needs: push-example-images
    steps:
      - name: Decrypt Images
        run: |
          echo -e "${{ secrets.DECRYPTION_KEY }}" | gpg --import
          echo -e "${{ needs.push-example-images.outputs.image-urls }}" | gpg --decrypt
