name: Generate Security Policy

on:
  workflow_call:
    inputs:
      test:
        description: "Test to generate Security Policy for"
        required: true
        type: string

jobs:
  generate-security-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Log into Azure
      #   run: |
      #     az login --service-principal \
      #       --username ${{ secrets.SP_APP_ID }} \
      #       --password ${{ secrets.SP_PASSWORD }} \
      #       --tenant ${{ secrets.SP_TENANT }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZ_REGISTRY_LOGIN }}
          username: ${{ secrets.AZ_REGISTRY_USERNAME }}
          password: ${{ secrets.AZ_REGISTRY_PASSWORD }}

      - name: Install dependencies
        run: az extension add --name confcom

      - name: Download ARM Template Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.inputs.test }}_arm_template

      - name: Give user permission to run docker
        run: sudo usermod -aG docker $USER

      - name: Generate Security Policy
        id: generate-security-policy
        run: |
          az confcom acipolicygen \
              -a ${{ github.event.inputs.test }}_arm_template.json \
              --outraw \
              --save-to-file ${{ github.event.inputs.test }}_security_policy.rego

      - name: Upload Security Policy Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.test }}_security_policy
          path: ${{ github.event.inputs.test }}_security_policy.rego
