name: Generate ARM Template

on:
  workflow_dispatch:
    inputs:
      id:
        description: "Unique Identifier for this run"
        required: true
        type: string
      test:
        description: "Test to generate the ARM template for"
        required: true
        type: choice
        options:
          - simple_server
      location:
        description: "Location to deploy to"
        required: true
        type: string
      security-policy:
        description: "Security policy to use for ACI"
        required: true
        type: string
  workflow_call:
    inputs:
      id:
        description: "Unique Identifier for this run"
        required: true
        type: string
      test:
        description: "Test to generate the ARM template for"
        required: true
        type: string
      location:
        description: "Location to deploy to"
        required: true
        type: string
      security-policy:
        description: "Security policy to use for ACI"
        required: true
        type: string

jobs:
  generate-arm-template:
    name: Generate ARM Template (${{ inputs.location }}/${{ inputs.security-policy }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate Matrix Cell Name
        id: generate-name
        run: echo "::set-output name=name::$(echo ${{ inputs.test }}-${{ inputs.location }}-${{ inputs.security-policy }}-${{ inputs.id }} | md5sum | sed 's/ //g' | sed 's/-//g')"

      - name: Download Security Policy Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.test }}_security_policies
          path: security_policies

      - name: Generate ARM Template
        id: generate-arm-template
        run: |
          python infra/generate_arm_template.py \
            --container-group-name group-${{ steps.generate-name.outputs.name }} \
            --location ${{ inputs.location }} \
            --manifest-path tests/${{ inputs.test }}/manifest.json \
            --security-policy "$(cat security_policies/${{ inputs.security-policy }} | base64)" \
            --registry-password ${{ secrets.AZ_REGISTRY_PASSWORD }} \
            --out arm_template.json

      - name: Print ARM Template
        run: cat arm_template.json

      - name: Upload ARM Template Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.generate-name.outputs.name }}_arm_template
          path: arm_template.json
