name: Generate Security Policy

on:
  workflow_call:
    inputs:
      test:
        description: "Test to generate Security Policy for"
        required: true
        type: string
      location:
        description: "Location to deploy ACI to"
        required: true
        type: string

jobs:
  generate-security-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: az extension add --name confcom

      - name: Download ARM Template Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.test }}_${{ inputs.location }}_arm_template

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZ_REGISTRY_LOGIN }}
          username: ${{ secrets.AZ_REGISTRY_USERNAME }}
          password: ${{ secrets.AZ_REGISTRY_PASSWORD }}

      - name: Set Docker Permissions
        run: sudo usermod -aG docker $USER

      - name: Generate Security Policy
        id: generate-security-policy
        run: |
          az confcom acipolicygen \
              -a arm_template.json \
              --outraw \
              --save-to-file ${{ inputs.test }}_${{ inputs.location }}_security_policy.rego

      - name: Print Security Policy
        run: cat ${{ inputs.test }}_${{ inputs.location }}_security_policy.rego

      - name: Upload Security Policy Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.test }}_${{ inputs.location }}_security_policy
          path: ${{ inputs.test }}_${{ inputs.location }}_security_policy.rego
