name: Generate ARM Template

on:
  workflow_call:
    inputs:
      test:
        description: "Test to generate ARM template for"
        required: true
        type: string
      location:
        description: "Location to deploy ACI to"
        required: true
        type: string

jobs:
  generate-arm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate ARM Template
        id: generate-arm-template
        run: |
          DASH_CASE_TEST=$(echo ${{ inputs.test }} | sed 's/_/-/g')
          python infra/generate_arm_template.py \
            --name $DASH_CASE_TEST-${{ github.run_id }}-${{ github.job }} \
            --location ${{ inputs.location }} \
            --image caciexamples.azurecr.io/${{ inputs.test }}:latest \
            --registry-password ${{ secrets.AZ_REGISTRY_PASSWORD }} \
            > ${{ inputs.test }}_arm_template.json

      - name: Print ARM Template
        run: cat ${{ inputs.test }}_arm_template.json

      - name: Upload ARM Template Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.test }}_arm_template
          path: ${{ inputs.test }}_arm_template.json
