name: Generate ARM Template

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to generate ARM template for"
        required: true
        type: choice
        options: ["simple_server"]

jobs:
  generate-arm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r infra/requirements.txt
          az extension add --name confcom

      - name: Generate ARM Template
        id: generate-arm-template
        run: |
          python infra/containers.py generate_arm_template \
            --name ${{ github.event.inputs.test }} \
            --image ${{ secrets.AZ_REGISTRY_LOGIN }}/${{ github.event.inputs.test }}:latest \
            --registry-password ${{ secrets.AZ_REGISTRY_PASSWORD }}
            --arm-out tests/${{ github.event.inputs.test }}/arm_template.json
        continue-on-error: true

      - name: Upload ARM Template Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.test }}_arm_template
          path: tests/${{ github.event.inputs.test }}/arm_template.json
        if: steps.generate-arm-template.outcome == 'success'
