name: Generate ARM Template

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to generate ARM template for"
        required: true
        type: choice
        options: ["simple_server"]
  workflow_call:
    inputs:
      test:
        description: "Test to generate ARM template for"
        required: true
        type: string

jobs:
  generate-arm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate ARM Template
        id: generate-arm-template
        run: |
          DASH_CASE_TEST=$(echo ${{ github.event.inputs.test }} | sed 's/_/-/g')
          python infra/generate_arm_template.py \
            --name $DASH_CASE_TEST \
            --image caciexamples.azurecr.io/${{ github.event.inputs.test }}:latest \
            > ${{ github.event.inputs.test }}_arm_template.json

      - name: Upload ARM Template Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.test }}_arm_template
          path: ${{ github.event.inputs.test }}_arm_template.json
