name: Manually Remove Containers

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      id:
        description: ID of the deployment
        required: true
        type: string
      example-name:
        description: Name of the example
        required: true
        type: string
      location:
        description: The location which the deployment belonged to
        required: true
        default: "westeurope"
        type: string
      security-policy:
        description: Name of the security policy which was used
        required: true
        default: _generated.rego
        type: string

jobs:
  
  resolve-manifest:
    name: Resolve Manifest Variables
    uses: ./.github/workflows/_resolve_manifest.yml
    secrets: inherit
    with:
      manifest: examples/${{ inputs.example-name }}/manifest.json

  remove-aci:
    name: Remove Containers
    uses: ./.github/workflows/_aci_remove.yml
    needs: resolve-manifest
    secrets: inherit
    with:
      id: ${{ inputs.id }}
      manifest: ${{ needs.resolve-manifest.outputs.manifest}}
      location: ${{ inputs.location }}
      security-policy: ${{ inputs.security-policy }}
