name: Push Example Image

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to push the image with
        required: true
        type: string
      test-name:
        description: Name of the Test
        required: true
        type: string
      image:
        description: Image to Push (e.g. primary:path/to/Dockerfile)
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        description: Tag to push the image with
        required: true
        type: string
      test-name:
        description: Name of the Test
        required: true
        type: string
      image:
        description: Image to Push (e.g. primary:path/to/Dockerfile)
        required: true
        type: string
jobs:
  push-example-image:
    name: Push Example Image (${{ inputs.image }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_REGISTRY_URL }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Get Docker Info
        id: docker-info
        run: |
          echo "repository=$(echo ${{ inputs.image }} | cut -d':' -f1 )" >> $GITHUB_OUTPUT
          echo "file=$(echo ${{ inputs.image }} | cut -d':' -f2 )" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: examples
          file: examples/${{ steps.docker-info.outputs.file }}
          push: true
          build-args: |
            RUN_ID=${{ inputs.tag }}
            AZURE_HSM_ENDPOINT=${{ secrets.AZURE_HSM_ENDPOINT }}
            AZURE_ATTESTATION_ENDPOINT=${{ secrets.AZURE_ATTESTATION_ENDPOINT }}
            AZURE_SERVICE_PRINCIPAL_APP_ID=${{ secrets.AZURE_SERVICE_PRINCIPAL_APP_ID }}
            AZURE_SERVICE_PRINCIPAL_PASSWORD=${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }}
            AZURE_SERVICE_PRINCIPAL_TENANT=${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}
          tags: |
            ${{ secrets.AZURE_REGISTRY_URL }}/${{ inputs.test-name }}/${{ steps.docker-info.outputs.repository }}:${{ inputs.tag }}