name: Push All Example Images

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      example-name:
        description: Name of example to test
        type: string
  workflow_dispatch:
    inputs:
      example-name:
        description: Name of example to test
        type: string

jobs:
  resolve-manifest:
    name: Resolve Manifest Variables
    uses: ./.github/workflows/_resolve_manifest.yml
    secrets: inherit
    with:
      manifest: examples/${{ inputs.example-name }}/manifest.json

  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    needs: resolve-manifest
    outputs:
      images: ${{ steps.get-images.outputs.images }}
    steps:
      - name: Decrypt Manifest
        run: |
          echo -e "${{ secrets.DECRYPTION_KEY }}" | gpg --import
          echo -e "${{ needs.resolve-manifest.outputs.manifest }}" | gpg --decrypt > manifest.json
        
      - name: Get Images
        id: get-images
        run: echo "images=[$(cat manifest.json | jq -r '.images | to_entries[] | "\"\(.key):\(.value)\","' | tr -d '\n')]" >> $GITHUB_OUTPUT
          
  push-example-images:
    name: Push Example Images
    uses: ./.github/workflows/push_example_image.yml
    secrets: inherit
    if: ${{ needs.prepare.outputs.images != '[]' }}
    needs: [prepare, resolve-manifest]
    strategy:
      matrix:
        image: ${{ fromJson(needs.prepare.outputs.images) }}
    with:
      tag: latest
      test-name: ${{ inputs.example-name }}
      image: ${{ matrix.image }}