name: Push Latest Simple Server Image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/push_latest_simple_server.yml
      - examples/simple_server/**
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Manifest
        uses: actions/upload-artifact@v3
        with:
          name: latest_manifest
          path: examples/simple_server/manifest.json

  push-latest-simple-server:
    name: "Push Latest Simple Server Image"
    uses: ./.github/workflows/build_and_push_images.yml
    secrets: inherit
    with:
      id: latest
      test: simple_server
