name: Push Latest Images

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/push_images.yml
      - examples/**
  workflow_dispatch:

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.attestation }}
      output2: ${{ steps.filter.outputs.key_release }}
      output3: ${{ steps.filter.outputs.encrypted_filesystem }}
      output4: ${{ steps.filter.outputs.simple_server }}
      output5: ${{ steps.filter.outputs.simple_sidecar }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
            filters: |
            attestation:
                - 'examples/attestation/**'
            key_release:
                - 'examples/key_release/**'
            encrypted_filesystem:
                - 'examples/encrypted_filesystem/**'
            simple_server:
                - 'examples/simple_server/**'
            simple_sidecar:
                - 'examples/simple_sidecar/**'
        # run only if 'attestation' files were changed
      - name: Push Latest Attestation Image
        if: steps.filter.outputs.attestation == 'true'
        uses: ./.github/workflows/push_all_example_images.yml
        secrets: inherit
        with:
          example-name: attestation
          tag: latest

        # run only if 'key_release' files were changed
      - name: Push Latest Key Release Image
        if: steps.filter.outputs.key_release == 'true'
        uses: ./.github/workflows/push_all_example_images.yml
        secrets: inherit
        with:
          example-name: key_release
          tag: latest

        # run only if 'encrypted_filesystem' files were changed
      - name: Push Latest Encrypted Filesystem Image
        if: steps.filter.outputs.encrypted_filesystem == 'true'
        uses: ./.github/workflows/push_all_example_images.yml
        secrets: inherit
        with:
          example-name: encrypted_filesystem
          tag: latest

        # run only if 'simple_server' files were changed
      - name: Push Latest Simple Server Image
        if: steps.filter.outputs.simple_server == 'true'
        uses: ./.github/workflows/push_all_example_images.yml
        secrets: inherit
        with:
          example-name: simple_server
          tag: latest

        # run only if 'simple_sidecar' files were changed
      - name: Push Latest Simple Sidecar Images
        if: steps.filter.outputs.simple_sidecar == 'true'
        uses: ./.github/workflows/push_all_example_images.yml
        secrets: inherit
        with:
          example-name: simple_sidecar
          tag: latest
    
