name: Push Latest Attestation Image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/push_latest_attestation.yml
      - examples/attestation/**
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Manifest
        uses: actions/upload-artifact@v3
        with:
          name: latest_manifest
          path: examples/attestation/manifest.json

  push-latest-attestation:
    name: "Push Latest Attestation Image"
    uses: ./.github/workflows/build_and_push_images.yml
    secrets: inherit
    with:
      id: latest
      test: attestation
