name: Push Latest Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  push-latest-simple-server:
    name: "Push Latest Simple Server Image"
    uses: ./.github/workflows/build_and_push_images.yml
    secrets: inherit
    with:
      id: latest
      test: simple_server

  push-latest-simple-sidecar:
    name: "Push Latest Simple Sidecar Images"
    uses: ./.github/workflows/build_and_push_images.yml
    secrets: inherit
    with:
      id: latest
      test: simple_sidecar

  push-latest-attestation:
    name: "Push Latest Attestation Image"
    uses: ./.github/workflows/build_and_push_images.yml
    secrets: inherit
    with:
      id: latest
      test: attestation