name: Push Latest Simple Sidecar Images

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/push_latest_simple_sidecar.yml
      - examples/simple_sidecar/**
  workflow_dispatch:

jobs:
  push-latest-simple-sidecar:
    name: "Push Latest Simple Sidecar Images"
    uses: ./.github/workflows/build_and_push_images.yml
    secrets: inherit
    with:
      id: latest
      test: simple_sidecar
