name: Push Latest Simple Server Image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/push_latest_simple_server.yml
      - examples/simple_server/**
  workflow_dispatch:

jobs:
  push-latest-simple-server:
    name: "Push Latest Simple Server Image"
    uses: ./.github/workflows/build_and_push_images.yml
    secrets: inherit
    with:
      id: latest
      test: simple_server
