name: Push Example Image

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to push the image with
        required: true
        type: string
      test-name:
        description: Name of the Test
        required: true
        type: string
      image:
        description: Image to Push (e.g. primary:path/to/Dockerfile)
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        description: Tag to push the image with
        required: true
        type: string
      test-name:
        description: Name of the Test
        required: true
        type: string
      image:
        description: Image to Push (e.g. primary:path/to/Dockerfile)
        required: true
        type: string

jobs:
  push-example-image:
    name: Push Example Image (${{ inputs.image }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_SERVICE_PRINCIPAL_APP_ID }}
          tenant-id: ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ secrets.AZURE_REGISTRY_USERNAME }}

      - name: Get Docker Info
        id: docker-info
        run: |
          echo "repository=$(echo ${{ inputs.image }} | cut -d':' -f1 )" >> $GITHUB_OUTPUT
          echo "file=$(echo ${{ inputs.image }} | cut -d':' -f2 )" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: examples
          file: examples/${{ steps.docker-info.outputs.file }}
          push: true
          tags: |
            ${{ secrets.AZURE_REGISTRY_URL }}/${{ inputs.test-name }}/${{ steps.docker-info.outputs.repository }}:${{ inputs.tag }}