name: Remove Container

on:
  workflow_dispatch:
    inputs:
      id:
        description: "Unique Identifier for this run"
        required: true
        type: string
      test:
        description: "Test to remove the ACI for"
        required: true
        type: choice
        options:
          - simple_server
      location:
        description: "Location to deploy ACI to"
        required: true
        type: string
      security-policy:
        description: "Security policy within the artifact to use for ACI"
        required: true
        type: string
  workflow_call:
    inputs:
      id:
        description: "Unique Identifier for this run"
        required: true
        type: string
      test:
        description: "Test to remove the ACI for"
        required: true
        type: string
      location:
        description: "Location to deploy ACI to"
        required: true
        type: string
      security-policy:
        description: "Security policy within the artifact to use for ACI"
        required: true
        type: string

jobs:
  remove-container:
    name: Remove Container (${{ inputs.location }}/${{ inputs.security-policy }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Log into Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.SP_APP_ID }} \
            --password ${{ secrets.SP_PASSWORD }} \
            --tenant ${{ secrets.SP_TENANT }}

      - name: Remove Container on ACI
        run: |
          python infra/remove_container.py \
            --subscription-id ${{ secrets.AZ_SUBSCRIPTION_ID }} \
            --resource-group ${{ secrets.AZ_RESOURCE_GROUP }} \
            --deployment-name deployment-${{ inputs.id }}
