name: Run All Tests

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simple-server:
    name: Simple Server Test
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: simple_server
