name: Run All Tests

on:
  workflow_dispatch:

jobs:
  simple-server:
    name: Simple Server
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: simple_server

  simple-sidecar:
    name: Simple Sidecar
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: simple_sidecar

  attestation:
    name: Attestation
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: attestation

  remote-image:
    name: Remote Image
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: remote_image

  key-release:
    name: Key Release
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: key_release
