name: Run Single Test

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: choice
        options:
          - simple_server

jobs:
  run-single-tests:
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: ${{ github.event.inputs.test }}
