name: Run Test

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: choice
        options:
          - simple_server
      location:
        description: "Locations to deploy ACIs to"
        default: '["eastus2euap", "westeurope"]'
        required: false
        type: string
  workflow_call:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: string
      locations:
        description: "Locations to deploy ACIs to"
        default: '["eastus2euap", "westeurope"]'
        required: false
        type: string

jobs:
  build-and-push-images:
    name: " "
    uses: ./.github/workflows/_build_and_push_images.yml
    secrets: inherit
    with:
      test: ${{ inputs.test }}

  generate-security-policy:
    name: " "
    uses: ./.github/workflows/_generate_security_policy.yml
    needs: build-and-push-images
    secrets: inherit
    with:
      test: ${{ inputs.test }}

  generate-arm-templates:
    uses: ./.github/workflows/_generate_arm_template.yml
    needs: generate-security-policy
    secrets: inherit
    strategy:
      matrix:
        location: ${{ fromJson(inputs.locations) }}
        security-policy: ${{ fromJson(needs.generate-security-policy.outputs.security-policies) }}
    with:
      test: ${{ inputs.test }}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}

  deploy-containers:
    uses: ./.github/workflows/_deploy_container.yml
    needs: [generate-security-policy, generate-arm-templates]
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJson(inputs.locations) }}
        security-policy: ${{ fromJson(needs.generate-security-policy.outputs.security-policies) }}
    with:
      test: ${{ inputs.test }}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}

  remove-containers:
    uses: ./.github/workflows/_remove_container.yml
    needs: [generate-security-policy, deploy-containers]
    secrets: inherit
    if: always()
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJson(inputs.locations) }}
        security-policy: ${{ fromJson(needs.generate-security-policy.outputs.security-policies) }}
    with:
      test: ${{ inputs.test }}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}

  # deploy-and-run:
  #   name: " "
  #   uses: ./.github/workflows/_deploy_and_run.yml
  #   needs: generate-security-policy
  #   secrets: inherit
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       location: ${{ fromJson(inputs.locations) }}
  #       security-policy: ${{ fromJson(needs.generate-security-policy.outputs.security-policies) }}
  #   with:
  #     test: ${{ inputs.test }}
  #     location: ${{ matrix.location }}
  #     image: ${{ vars.REGISTRY }}/${{ inputs.test }}:latest
  #     security-policy-artifact-name: ${{ inputs.test }}_security_policies
  #     security-policy: ${{ matrix.security-policy }}
