name: Run Test

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: choice
        options:
          - simple_server
      location:
        description: "Locations to deploy ACIs to"
        default: '["eastus2euap", "westeurope"]'
        required: false
        type: string
  workflow_call:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: string
      locations:
        description: "Locations to deploy ACIs to"
        default: '["eastus2euap", "westeurope"]'
        required: false
        type: string

jobs:

  workflow-id:
    name: "Generate Workflow ID"
    runs-on: ubuntu-latest
    outputs:
      workflow-id: ${{ steps.workflow-id.outputs.workflow-id }}
    steps:
      - name: "Get Workflow ID"
        id: workflow-id
        run: |
          WORKFLOW_ID=$(openssl rand -hex 8 | tr -d '\n')
          echo $WORKFLOW_ID
          echo "workflow-id=$WORKFLOW_ID" >> $GITHUB_OUTPUT

  build-and-push-images:
    name: "Build and Push Images"
    uses: ./.github/workflows/build_and_push_images.yml
    needs: workflow-id
    secrets: inherit
    with:
      id: ${{ needs.workflow-id.outputs.workflow-id }}
      test: ${{ inputs.test }}

  generate-security-policy:
    name: "Generate Security Policy"
    uses: ./.github/workflows/generate_security_policy.yml
    needs: [workflow-id, build-and-push-images]
    secrets: inherit
    with:
      id: ${{ needs.workflow-id.outputs.workflow-id }}
      test: ${{ inputs.test }}

  generate-arm-templates:
    name: "Generate ARM Templates"
    uses: ./.github/workflows/generate_arm_template.yml
    needs: [workflow-id, generate-security-policy]
    secrets: inherit
    strategy:
      matrix:
        location: ${{ fromJson(inputs.locations) }}
        security-policy: ${{ fromJson(needs.generate-security-policy.outputs.security-policies) }}
    with:
      id: ${{ needs.workflow-id.outputs.workflow-id }}
      test: ${{ inputs.test }}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}

  deploy-containers:
    name: "Deploy Containers"
    uses: ./.github/workflows/deploy_container.yml
    needs: [workflow-id, generate-security-policy, generate-arm-templates]
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJson(inputs.locations) }}
        security-policy: ${{ fromJson(needs.generate-security-policy.outputs.security-policies) }}
    with:
      id: ${{ needs.workflow-id.outputs.workflow-id }}
      test: ${{ inputs.test }}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}

  client-side-tests:
    name: "Run Client Side Tests"
    uses: ./.github/workflows/client_side_test.yml
    needs: [workflow-id, generate-security-policy, deploy-containers]
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJson(inputs.locations) }}
        security-policy: ${{ fromJson(needs.generate-security-policy.outputs.security-policies) }}
    with:
      id: ${{ needs.workflow-id.outputs.workflow-id }}
      test: ${{ inputs.test }}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}

  remove-containers:
    name: "Remove Containers"
    uses: ./.github/workflows/remove_container.yml
    needs: [workflow-id, generate-security-policy, client-side-tests]
    secrets: inherit
    if: always()
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJson(inputs.locations) }}
        security-policy: ${{ fromJson(needs.generate-security-policy.outputs.security-policies) }}
    with:
      id: ${{ needs.workflow-id.outputs.workflow-id }}
      test: ${{ inputs.test }}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}
