name: Run All Tests

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-simple-server:
    uses: ./.github/workflows/end_to_end_test.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test: [simple_server]
        location: [eastus2euap, northeurope]
    with:
      test: ${{ matrix.test }}
      location: ${{ matrix.location }}
