name: Run All Tests

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-all:
    name: Run All Tests
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test: [simple_server]
    with:
      test: ${{ matrix.test }}
