name: Run Test

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: choice
        options:
          - simple_server
      location:
        description: "Locations to deploy ACIs to"
        default: '["eastus2euap", "westeurope"]'
        required: false
        type: string
  workflow_call:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: string
      locations:
        description: "Locations to deploy ACIs to"
        default: '["eastus2euap", "westeurope"]'
        required: false
        type: string

jobs:
  build-and-push-image:
    name: ""
    uses: ./.github/workflows/_build_and_push_image.yml
    secrets: inherit
    with:
      label: ${{ inputs.test }}
      dockerfile: tests/${{ inputs.test }}/Dockerfile
      tag: ${{ vars.REGISTRY }}/${{ inputs.test }}:latest

  generate-security-policy:
    name: ""
    uses: ./.github/workflows/_generate_security_policy.yml
    needs: build-and-push-image
    secrets: inherit
    with:
      image: ${{ vars.REGISTRY }}/${{ inputs.test }}:latest
      test: ${{ inputs.test }}
      artifact-name: ${{ inputs.test }}_security_policies

  deploy-and-run:
    name: ""
    uses: ./.github/workflows/_deploy_and_run.yml
    needs: generate-security-policy
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJson(inputs.locations) }}
        security-policy: ${{ fromJson(needs._1.outputs.security-policies) }}
    with:
      test: ${{ inputs.test }}
      location: ${{ matrix.location }}
      image: ${{ vars.REGISTRY }}/${{ inputs.test }}:latest
      security-policy-artifact-name: ${{ inputs.test }}_security_policies
      security-policy: ${{ matrix.security-policy }}
