name: Run Tests

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: choice
        options: ["simple_server"]

jobs:
  generate-arm-template:
    uses: ./.github/workflows/generate_arm_template.yml
    secrets: inherit
    with:
      test: ${{ github.event.inputs.test }}

  generate-security-policy:
    uses: ./.github/workflows/generate_security_policy.yml
    secrets: inherit
    needs: generate-arm-template
    with:
      test: ${{ github.event.inputs.test }}

  add-security-policy-to-arm-template:
    uses: ./.github/workflows/add_security_policy_to_arm_template.yml
    needs: generate-security-policy
    with:
      test: ${{ github.event.inputs.test }}

  deploy-container:
    uses: ./.github/workflows/deploy_container.yml
    secrets: inherit
    needs: add-security-policy-to-arm-template
    with:
      test: ${{ github.event.inputs.test }}

  run-test:
    runs-on: ubuntu-latest
    needs: deploy-container
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: |
          python -m unittest \
            tests.${{ github.event.inputs.test }}.${{ github.event.inputs.test }}_test \
            -v

  remove-container:
    uses: ./.github/workflows/remove_container.yml
    secrets: inherit
    needs: run-test
    with:
      test: ${{ github.event.inputs.test }}
