name: Run Tests

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: choice
        options: ["simple_server"]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r infra/requirements.txt

      - name: Log into Azure
        run: az login --service-principal --username ${{ secrets.SP_APP_ID }} --password ${{ secrets.SP_PASSWORD }} --tenant ${{ secrets.SP_TENANT }}

      - name: Run Tests
        run: |
          python -m unittest \
            tests.${{ github.event.inputs.test }}.${{ github.event.inputs.test }}_test \
            -v
