name: Run Single Test

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Test to run"
        required: true
        type: choice
        options:
          - simple_server
      location:
        description: "Location to deploy ACI to"
        required: true
        type: string
        default: eastus2euap

jobs:
  run-single-test:
    uses: ./.github/workflows/end_to_end_test.yml
    secrets: inherit
    with:
      test: ${{ inputs.test }}
      location: ${{ inputs.location }}
