name: Run Tests

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test to run'
        required: true
        type: choice
        options: [
          "simple_server",
        ]

jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Tests
          run: python tests/${{ github.event.inputs.test }}/${{ github.event.inputs.test }}_test.py
