name: Run All Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simple-server:
    name: Simple Server
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: simple_server
