name: Status of West Europe

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  simple-server-0:
    name: Simple Server
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '["westeurope"]'

  simple-server-1:
    name: Simple Server
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '["westeurope"]'

  simple-server-2:
    name: Simple Server
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '["westeurope"]'
