name: Regional Status (Large Containers)

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

env:
  LOCATIONS: '["eastus2euap", "northeurope", "westeurope"]'

jobs:
  simple-server-8gb:
    name: Simple Server 8GB
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '$LOCATIONS'
      manifest-modifiers: "SIMPLE_SERVER_CORES=4;SIMPLE_SERVER_RAM=8"

  simple-server-16gb:
    name: Simple Server 16GB
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '$LOCATIONS'
      manifest-modifiers: "SIMPLE_SERVER_CORES=4;SIMPLE_SERVER_RAM=16"

  simple-server-16core:
    name: Simple Server 16 Cores
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '$LOCATIONS'
      manifest-modifiers: "SIMPLE_SERVER_CORES=16;SIMPLE_SERVER_RAM=16"
      
  simple-server-32core:
    name: Simple Server 32 Cores
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '$LOCATIONS'
      manifest-modifiers: "SIMPLE_SERVER_CORES=32;SIMPLE_SERVER_RAM=32"