name: Status of North Europe

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  simple-server-northeurope:
    name: Simple Server on North Europe
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: simple_server
      locations: '["northeurope"]'
