name: Regional Status

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

env:
  LOCATIONS: '["eastus2euap", "northeurope", "westeurope"]'

jobs:
  simple-server-0:
    name: Simple Server
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '$LOCATIONS'

  simple-server-1:
    name: Simple Server
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '$LOCATIONS'

  simple-server-2:
    name: Simple Server
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '$LOCATIONS'
