name: Status of West Europe

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  simple-server-westeurope:
    name: Simple Server on West Europe
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: simple_server
      locations: '["westeurope"]'
