name: Regional Status

on:
  schedule:
    - cron: "0 7 * * *"
  pull_request:
    paths:
      - .github/workflows/status.yml
  workflow_dispatch:
    inputs:
      locations:
        required: false
        default: '["northeurope", "westeurope"]'

jobs:
  simple-server-0:
    name: Simple Server
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: ${{ inputs.locations || '["northeurope", "westeurope"]' }}

  simple-server-1:
    name: Simple Server
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: ${{ inputs.locations || '["northeurope", "westeurope"]' }}

  simple-server-2:
    name: Simple Server
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: ${{ inputs.locations || '["northeurope", "westeurope"]' }}

  simple-server-8gb:
    name: Simple Server 8GB
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: ${{ inputs.locations || '["northeurope", "westeurope"]' }}
      manifest-modifiers: "SIMPLE_SERVER_CORES=4;SIMPLE_SERVER_RAM=8"
    
  simple-server-16gb:
    name: Simple Server 16GB
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: ${{ inputs.locations || '["northeurope", "westeurope"]' }}
      manifest-modifiers: "SIMPLE_SERVER_CORES=4;SIMPLE_SERVER_RAM=16"
