name: Status of West Europe

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  simple-server-westeurope-0:
    name: Simple Server on East US 2 EUAP
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: simple_server
      locations: '["westeurope"]'

  simple-server-westeurope-1:
    name: Simple Server on East US 2 EUAP
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: simple_server
      locations: '["westeurope"]'

  simple-server-westeurope-2:
    name: Simple Server on East US 2 EUAP
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: simple_server
      locations: '["westeurope"]'
