name: Status of East US 2 EUAP

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  simple-server-eastus2euap:
    name: Simple Server on East US 2 EUAP
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: simple_server
      locations: '["eastus2euap"]'
