name: Status of East US 2 EUAP

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  simple-server-8gb:
    name: Simple Server
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '["eastus2euap"]'
      manifest-modifiers: "SIMPLE_SERVER_CORES=4;SIMPLE_SERVER_RAM=8"

  simple-server-16gb:
    name: Simple Server
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '["eastus2euap"]'
      manifest-modifiers: "SIMPLE_SERVER_CORES=4;SIMPLE_SERVER_RAM=16"