name: Test Key Release

on:
  workflow_call:
    inputs:
      key-release-image:
        description: "The image of the SKR sidecar to use"
        required: false
        default: "http://mcr.microsoft.com/aci/skr:2.5"
        type: string
  workflow_dispatch:
    inputs:
      key-release-image:
        description: "The image of the SKR sidecar to use"
        required: false
        default: "http://mcr.microsoft.com/aci/skr:2.5"
        type: string
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/key_release/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/key_release/**
  merge_group:
    branches:
      - main
  schedule:
    - cron: "0 7 * * *"

jobs:
  resolve-image:
    name: Resolve Sidecar Image
    runs-on: ubuntu-latest
    outputs:
      manifest-modifiers: ${{ steps.resolve-image.outputs.manifest-modifiers }}
    steps:
      - name: Define Image to Use
        id: resolve-image
        env:
          KEY_RELEASE_IMAGE: ${{ inputs.key-release-image }}
        run: |
          if [ -z "$KEY_RELEASE_IMAGE" ]; then
            KEY_RELEASE_IMAGE="http://mcr.microsoft.com/aci/skr:2.5"
          fi
          echo "manifest-modifiers=KEY_RELEASE_IMAGE=$KEY_RELEASE_IMAGE" >> $GITHUB_OUTPUT

  key-release:
    name: Key Release
    uses: ./.github/workflows/test_example.yml
    needs: resolve-image
    secrets: inherit
    with:
      example-name: key_release
      manifest-modifiers: ${{ needs.resolve-image.outputs.manifest-modifiers }}
