name: Test Key Release

on:
  workflow_call:
    inputs:
      key-release-image:
        description: "The image of the SKR sidecar to use"
        required: false
        default: "http://mcr.microsoft.com/aci/skr:2.3"
        type: string
  workflow_dispatch:
    inputs:
      key-release-image:
        description: "The image of the SKR sidecar to use"
        required: false
        default: "http://mcr.microsoft.com/aci/skr:2.3"
        type: string
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/key_release/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/key_release/**
  merge_group:
    branches:
      - main
  schedule:
    - cron: "0 7 * * *"

jobs:
  key-release:
    name: Key Release
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: key_release
      manifest-modifiers: "KEY_RELEASE_IMAGE=${{ inputs.key-release-image }}"
