name: Test Simple Sidecar

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/simple_sidecar/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/simple_sidecar/**
  merge_group:
    branches:
      - main

jobs:
  simple-sidecar:
    name: Simple Sidecar
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_sidecar
