name: Key Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/key_release/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/key_release/**
  merge_group:
    branches:
      - main

jobs:
  key_release:
    name: Key Release
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: key_release
