name: Attestation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/attestation/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/attestation/**
  merge_group:
    branches:
      - main
  schedule:
    - cron: "0 7 * * *"

jobs:
  attestation:
    name: Attestation
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: attestation
