name: Test Key Release (Latest)

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"
  pull_request:
    paths:
      - .github/workflows/test_key_release_latest.yml

jobs:
  key-release:
    name: Key Release
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: key_release
      manifest-modifiers: "KEY_RELEASE_IMAGE=http://confidentialsidecars.azurecr.io/skr:main"
