name: Encrypted Filesystem Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"
  pull_request:
    paths:
      - .github/workflows/test_encrypted_filesystem_daily.yml

jobs:
  prepare:
    name: Prepare Test
    runs-on: ubuntu-latest
    outputs:
      workflow-id: ${{ steps.workflow-id.outputs.workflow-id }}
    steps:
      - name: "Get Workflow ID"
        id: workflow-id
        run: |
          WORKFLOW_ID=$(openssl rand -hex 8 | tr -d '\n')
          echo $WORKFLOW_ID
          echo "workflow-id=$WORKFLOW_ID" >> $GITHUB_OUTPUT

  encrypted-filesystem:
    name: Encrypted Filesystem
    uses: ./.github/workflows/run_test.yml
    needs: prepare
    secrets: inherit
    with:
      id: ${{ needs.prepare.outputs.workflow-id }}
      test: encrypted_filesystem
      manifest-modifiers: "ENCRYPTED_FILESYSTEM_IMAGE=http://confidentialsidecars.azurecr.io/encfs:main"
