name: Simple Server

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/simple_server/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/simple_server/**
  merge_group:
    branches:
      - main

jobs:
  generate-id:
    name: Generate Unique ID
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.generate-id.outputs.id }}
    steps:
      - name: Get Workflow ID
        id: generate-id
        run: echo "id=$(openssl rand -hex 8 | tr -d '\n')" >> $GITHUB_OUTPUT
  
  resolve-manifest:
    name: Resolve Manifest Variables
    uses: ./.github/workflows/_resolve_manifest.yml
    secrets: inherit
    with:
      manifest: examples/simple_server/manifest.json
      modifiers: ""
          
  build-and-push-images:
    name: Build and Push Images
    uses: ./.github/workflows/build_and_push_images.yml
    secrets: inherit
    needs: generate-id
    with:
      id: ${{ needs.generate-id.outputs.id }}
      test: simple_server
      
  deploy_aci:
    name: Deploy Container Instance
    uses: ./.github/workflows/deploy_aci.yml
    secrets: inherit
    needs: [resolve-manifest, build-and-push-images]
    strategy:
      matrix:
        location: ["westeurope"]
        security-policy: ["_generated.rego"]
    with:
      id: ${{ needs.generate-id.outputs.id }}
      manifest: ${{ needs.resolve-manifest.outputs.manifest}}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}
