name: Simple Sidecar

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/simple_sidecar/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/simple_sidecar/**
  merge_group:
    branches:
      - main

jobs:
  prepare:
    name: Prepare Test
    runs-on: ubuntu-latest
    outputs:
      workflow-id: ${{ steps.workflow-id.outputs.workflow-id }}
    steps:
      - name: "Get Workflow ID"
        id: workflow-id
        run: |
          WORKFLOW_ID=$(openssl rand -hex 8 | tr -d '\n')
          echo $WORKFLOW_ID
          echo "workflow-id=$WORKFLOW_ID" >> $GITHUB_OUTPUT

  simple-sidecar:
    name: Simple Sidecar
    uses: ./.github/workflows/run_test.yml
    needs: prepare
    secrets: inherit
    with:
      id: ${{ needs.prepare.outputs.workflow-id }}
      test: simple_sidecar
