name: Encrypted Filesystem Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  encrypted-filesystem:
    name: Encrypted Filesystem
    uses: ./.github/workflows/test_encrypted_filesystem.yml
    secrets: inherit
    with:
      encrypted_filesystem_image: http://confidentialsidecars.azurecr.io/encfs:main
