name: Attestation

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/attestation/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/attestation/**
  merge_group:
    branches:
      - main
  schedule:
    - cron: "0 7 * * *"

jobs:
  prepare:
    name: Prepare Test
    runs-on: ubuntu-latest
    outputs:
      workflow-id: ${{ steps.workflow-id.outputs.workflow-id }}
    steps:
      - name: "Get Workflow ID"
        id: workflow-id
        run: |
          WORKFLOW_ID=$(openssl rand -hex 8 | tr -d '\n')
          echo $WORKFLOW_ID
          echo "workflow-id=$WORKFLOW_ID" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Resolve Variables
        id: resolve-variables
        env:
          AZURE_REGISTRY_URL: ${{ secrets.AZURE_REGISTRY_URL }}
          AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          UNIQUE_ID: ${{ steps.workflow-id.outputs.workflow-id }}
          ATTESTATION_SIDECAR_IMAGE: ${{ secrets.ATTESTATION_SIDECAR_IMAGE }}
        run: python infra/resolve_manifest_variables.py examples/attestation/manifest.json > manifest.json

      - name: Upload Manifest
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.workflow-id.outputs.workflow-id }}_manifest
          path: manifest.json

  attestation:
    name: Attestation
    uses: ./.github/workflows/run_test.yml
    needs: prepare
    secrets: inherit
    with:
      id: ${{ needs.prepare.outputs.workflow-id }}
      test: attestation
