name: Test Attestation

on:
  workflow_call:
    inputs:
      attestation-image:
        description: "The image of the Attestation sidecar to use"
        required: false
        default: "http://confidentialsidecars.azurecr.io/attestation:main"
        type: string
  workflow_dispatch:
    inputs:
      attestation-image:
        description: "The image of the Attestation sidecar to use"
        required: false
        default: "http://confidentialsidecars.azurecr.io/attestation:main"
        type: string
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/attestation/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/attestation/**
  merge_group:
    branches:
      - main
  schedule:
    - cron: "0 7 * * *"

jobs:
  attestation:
    name: Attestation
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: attestation
      manifest-modifiers: "ATTESTATION_SIDECAR_IMAGE=${{ inputs.attestation-image }}"
