name: Test Encrypted Filesystem

on:
  workflow_call:
    inputs:
      sidecar_registry:
        description: "The registry to get the image from"
        required: true
        default: "http://mcr.microsoft.com"
        type: string
      encrypted_filesystem_image:
        description: "The image of the ENCFS sidecar to use"
        required: false
        default: "aci/encfs:2.7"
        type: string
  workflow_dispatch:
    inputs:
      sidecar_registry:
        description: "The registry to get the image from"
        required: true
        type: choice
        options: 
          - http://mcr.microsoft.com
          - http://confidentialsidecars.azurecr.io
      encrypted_filesystem_image:
        description: "The image of the ENCFS sidecar to use"
        required: false
        default: "aci/encfs:2.7"
        type: string
  repository_dispatch:
    types:
      - encfs-test
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/encrypted_filesystem/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/encrypted_filesystem/**
  merge_group:
    branches:
      - main
  schedule:
    - cron: "0 7 * * *"

jobs:
  resolve-image:
    name: Resolve Sidecar Image
    runs-on: ubuntu-latest
    outputs:
      manifest-modifiers: ${{ steps.resolve-image.outputs.manifest-modifiers }}
    steps:
      - name: Define Image to Use
        id: resolve-image
        env:
          SIDECAR_REGISTRY: ${{ inputs.sidecar_registry }}
          ENCRYPTED_FILESYSTEM_IMAGE: ${{ inputs.encrypted_filesystem_image }}
          REPO_DISPATCH_TAG: ${{ github.event.client_payload.image_tag }}
        run: |
          if [ -z "$SIDECAR_REGISTRY" ]; then
            SIDECAR_REGISTRY="http://mcr.microsoft.com"
          fi
          if [ -n "$REPO_DISPATCH_TAG" ]; then
            ENCRYPTED_FILESYSTEM_IMAGE="encfs:$REPO_DISPATCH_TAG"
          elif [ -z "$ENCRYPTED_FILESYSTEM_IMAGE" ]; then
            ENCRYPTED_FILESYSTEM_IMAGE="aci/encfs:2.7"
          fi
          echo "manifest-modifiers=ENCRYPTED_FILESYSTEM_IMAGE=$SIDECAR_REGISTRY/$ENCRYPTED_FILESYSTEM_IMAGE" >> $GITHUB_OUTPUT

  pipeline-link-comment:
    name: Create Pipeline Link Comment in PR
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{ github.run_id }}
      PR_NUMBER: ${{ github.event.client_payload.pr_number }}
    steps:
      - name: Create Pipeline Link Repo Dispatch Request
        run: |
          curl --fail-with-body -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACC_REPO_DISPATCH_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/microsoft/confidential-sidecar-containers/dispatches \
          -d '{"event_type":"pipeline-link-comment","client_payload":{"pipeline_link":"https://github.com/microsoft/confidential-aci-examples/actions/runs/$RUN_ID","pr_number":"$PR_NUMBER"}}'

  encrypted-filesystem:
    name: Encrypted Filesystem
    uses: ./.github/workflows/test_example.yml
    needs: resolve-image
    secrets: inherit
    with:
      example-name: encrypted_filesystem
      manifest-modifiers: ${{ needs.resolve-image.outputs.manifest-modifiers }}
