name: Key Release

on:
  workflow_call:
    inputs:
      key_release_image:
        description: "The image of the SKR sidecar to use"
        required: false
        default: "http://mcr.microsoft.com/aci/skr:2.3"
        type: string
  workflow_dispatch:
    inputs:
      key_release_image:
        description: "The image of the SKR sidecar to use"
        required: false
        default: "http://mcr.microsoft.com/aci/skr:2.3"
        type: string
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/key_release/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/key_release/**
  merge_group:
    branches:
      - main
  schedule:
    - cron: "0 7 * * *"

jobs:
  prepare:
    name: Prepare Test
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.resolve-variables.outputs.manifest }}
      workflow-id: ${{ steps.workflow-id.outputs.workflow-id }}
    steps:
      - name: "Get Workflow ID"
        id: workflow-id
        run: |
          WORKFLOW_ID=$(openssl rand -hex 8 | tr -d '\n')
          echo $WORKFLOW_ID
          echo "workflow-id=$WORKFLOW_ID" >> $GITHUB_OUTPUT
          
      - name: Define Image to Use
        id: resolve-image
        env: 
          KEY_RELEASE_IMAGE: ${{ inputs.key_release_image }}
        run: |
          if [ -z "$KEY_RELEASE_IMAGE" ]; then
            KEY_RELEASE_IMAGE="http://mcr.microsoft.com/aci/skr:2.3"
          fi
          manifest-modifiers="KEY_RELEASE_IMAGE=$KEY_RELEASE_IMAGE"
          echo "manifest-modifiers=$manifest-modifiers;UNIQUE_ID=${{ steps.workflow-id.outputs.workflow-id }}" >> $GITHUB_OUTPUT

  key-release:
    name: Key Release
    uses: ./.github/workflows/run_test.yml
    needs: prepare
    secrets: inherit
    with:
      id: ${{ needs.prepare.outputs.workflow-id }}
      test: key_release
