name: Test Attestation

on:
  workflow_call:
    inputs:
      attestation-image:
        description: "The image of the Attestation sidecar to use"
        required: false
        default: "http://confidentialsidecars.azurecr.io/attestation:main"
        type: string
  workflow_dispatch:
    inputs:
      attestation-image:
        description: "The image of the Attestation sidecar to use"
        required: false
        default: "http://confidentialsidecars.azurecr.io/attestation:main"
        type: string
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/attestation/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/attestation/**
  merge_group:
    branches:
      - main
  schedule:
    - cron: "0 7 * * *"

jobs:
  resolve-image:
    name: Resolve Sidecar Image
    runs-on: ubuntu-latest
    outputs:
      manifest-modifiers: ${{ steps.resolve-image.outputs.manifest-modifiers }}
    steps:
      - name: Define Image to Use
        id: resolve-image
        env:
          ATTESTATION_SIDECAR_IMAGE: ${{ inputs.attestation-image }}
        run: |
          if [ -z "$ATTESTATION_SIDECAR_IMAGE" ]; then
            ATTESTATION_SIDECAR_IMAGE="http://confidentialsidecars.azurecr.io/attestation:main"
          fi
          echo "manifest-modifiers=ATTESTATION_SIDECAR_IMAGE=$ATTESTATION_SIDECAR_IMAGE" >> $GITHUB_OUTPUT

  attestation:
    name: Attestation
    uses: ./.github/workflows/test_example.yml
    needs: resolve-image
    secrets: inherit
    with:
      example-name: attestation
      manifest-modifiers: ${{ needs.resolve-image.outputs.manifest-modifiers }}
