name: Test Simple Server

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/simple_server/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/simple_server/**
  merge_group:
    branches:
      - main

jobs:
  simple-server:
    name: Simple Server
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server