name: Test Attestation (Canary)

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"
  pull_request:
    paths:
      - .github/workflows/test_attestation_canary.yml

jobs:
      
  attestation-canary-azurecr:
    name: Attestation (Azure CR)
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: attestation
      locations: '["eastus2euap"]'
      manifest-modifiers: "ATTESTATION_SIDECAR_IMAGE=http://confidentialsidecars.azurecr.io/attestation:main"
