name: Simple Server

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/simple_server/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/simple_server/**
  merge_group:
    branches:
      - main

jobs:

  resolve-manifest:
    name: Resolve Manifest Variables
    uses: ./.github/workflows/_resolve_manifest.yml
    secrets: inherit
    with:
      manifest: examples/simple_server/manifest.json
      modifiers: ""

  prepare:
    name: Prepare Test
    runs-on: ubuntu-latest
    needs: resolve-manifest
    outputs:
      id: ${{ steps.generate-id.outputs.id }}
      images: ${{ steps.get-images.outputs.images }}
      security-policies: ${{ steps.get-security-policies.outputs.security_policies }}
    steps:
      - name: Get Workflow ID
        id: generate-id
        run: echo "id=$(openssl rand -hex 8 | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Decrypt Manifest
        run: |
          echo -e "${{ secrets.DECRYPTION_KEY }}" | gpg --import
          echo -e "${{ needs.resolve-manifest.outputs.manifest }}" | gpg --decrypt > manifest.json
        
      - name: Get Images
        id: get-images
        run: |
          images="[$(cat manifest.json | jq -r ".images" | tr -d '{}\n')]"
          echo $images
          echo "images=$images" >> $GITHUB_OUTPUT

      - name: Get Security Policies
        id: get-security-policies
        run: |
          securityPolicies="[$(cat manifest.json | jq -r '.securityPolicies' | tr -d '{}\n'), \"_generated.rego\"]"
          echo $securityPolicies
          echo "security-policies=$securityPolicies" >> $GITHUB_OUTPUT
          
  build-and-push-images:
    name: Build and Push Images
    uses: ./.github/workflows/_push_example_image.yml
    secrets: inherit
    needs: [prepare, resolve-manifest]
    strategy:
      matrix:
        image: ${{ fromJson(needs.prepare.outputs.images) }}
    with:
      tag: ${{ needs.prepare.outputs.id }}
      test-name: simple_server
      image: ${{ matrix.image }}

  deploy-aci:
    name: Deploy Containers
    uses: ./.github/workflows/aci_deploy.yml
    secrets: inherit
    needs: [prepare, resolve-manifest, build-and-push-images]
    strategy:
      matrix:
        location: ["westeurope"]
        security-policy: ${{ fromJson(needs.prepare.outputs.security-policies) }}
    with:
      id: ${{ needs.prepare.outputs.id }}
      manifest: ${{ needs.resolve-manifest.outputs.manifest}}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}
      
  test-deployment:
    name: Test Deployment
    uses: ./.github/workflows/_test_deployment.yml
    needs: [prepare, resolve-manifest, deploy-aci]
    secrets: inherit
    strategy:
      matrix:
        location: ["westeurope"]
        security-policy: ${{ fromJson(needs.prepare.outputs.security-policies) }}
    with:
      id: ${{ needs.prepare.outputs.id }}
      manifest: ${{ needs.resolve-manifest.outputs.manifest}}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}

  remove-aci:
    name: Remove Containers
    uses: ./.github/workflows/aci_remove.yml
    needs: [prepare, resolve-manifest, test-deployment]
    secrets: inherit
    if: ${{ always() }}
    strategy:
      fail-fast: false
      matrix:
        location: ["westeurope"]
        security-policy: ${{ fromJson(needs.prepare.outputs.security-policies) }}
    with:
      id: ${{ needs.prepare.outputs.id }}
      manifest: ${{ needs.resolve-manifest.outputs.manifest}}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}
