name: Test Example

on:
  workflow_call:
    inputs:
      example-name:
        description: Name of example to test
        type: string
      manifest-modifiers:
        description: Modifications to environment for the manifest
        type: string
  workflow_dispatch:
    inputs:
      example-name:
        description: Name of example to test
        type: string
      manifest-modifiers:
        description: Modifications to environment for the manifest
        type: string

jobs:

  resolve-manifest:
    name: Resolve Manifest Variables
    uses: ./.github/workflows/_resolve_manifest.yml
    secrets: inherit
    with:
      manifest: examples/${{ inputs.example-name }}/manifest.json
      modifiers: ${{ inputs.manifest-modifiers }}

  prepare:
    name: Prepare Test
    runs-on: ubuntu-latest
    needs: resolve-manifest
    outputs:
      id: ${{ steps.generate-id.outputs.id }}
      images: ${{ steps.get-images.outputs.images }}
      security-policies: ${{ steps.get-security-policies.outputs.security-policies }}
    steps:
      - name: Get Workflow ID
        id: generate-id
        run: echo "id=$(openssl rand -hex 8 | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Decrypt Manifest
        run: |
          echo -e "${{ secrets.DECRYPTION_KEY }}" | gpg --import
          echo -e "${{ needs.resolve-manifest.outputs.manifest }}" | gpg --decrypt > manifest.json
        
      - name: Get Images
        id: get-images
        run: |
          images="[$(cat manifest.json | jq -r '.images | to_entries[] | "\"\(.key):\(.value)\","' | tr -d '\n')]"
          echo $images
          echo "images=$images" >> $GITHUB_OUTPUT

      - name: Get Security Policies
        id: get-security-policies
        run: |
          securityPolicies="[$(cat manifest.json | jq -r '.securityPolicies' | tr -d '[]\n') \"_generated.rego\"]"
          echo $securityPolicies
          echo "security-policies=$securityPolicies" >> $GITHUB_OUTPUT
          
  push-example-images:
    name: Push Example Images
    uses: ./.github/workflows/push_example_image.yml
    secrets: inherit
    needs: [prepare, resolve-manifest]
    strategy:
      matrix:
        image: ${{ fromJson(needs.prepare.outputs.images) }}
    with:
      tag: ${{ needs.prepare.outputs.id }}
      test-name: ${{ inputs.example-name }}
      image: ${{ matrix.image }}

  deploy-aci:
    name: Deploy Containers
    uses: ./.github/workflows/_aci_deploy.yml
    secrets: inherit
    needs: [prepare, resolve-manifest, push-example-images]
    strategy:
      matrix:
        location: ["westeurope"]
        security-policy: ${{ fromJson(needs.prepare.outputs.security-policies) }}
    with:
      id: ${{ needs.prepare.outputs.id }}
      manifest: ${{ needs.resolve-manifest.outputs.manifest}}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}
      
  test-deployment:
    name: Test Deployment
    uses: ./.github/workflows/_test_deployment.yml
    needs: [prepare, resolve-manifest, deploy-aci]
    secrets: inherit
    strategy:
      matrix:
        location: ["westeurope"]
        security-policy: ${{ fromJson(needs.prepare.outputs.security-policies) }}
    with:
      id: ${{ needs.prepare.outputs.id }}
      manifest: ${{ needs.resolve-manifest.outputs.manifest}}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}

  remove-aci:
    name: Remove Containers
    uses: ./.github/workflows/_aci_remove.yml
    needs: [prepare, resolve-manifest, test-deployment]
    secrets: inherit
    if: ${{ always() }}
    strategy:
      fail-fast: false
      matrix:
        location: ["westeurope"]
        security-policy: ${{ fromJson(needs.prepare.outputs.security-policies) }}
    with:
      id: ${{ needs.prepare.outputs.id }}
      manifest: ${{ needs.resolve-manifest.outputs.manifest}}
      location: ${{ matrix.location }}
      security-policy: ${{ matrix.security-policy }}