name: Test Sidecar Images in Canary Region

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"
  pull_request:
    paths:
      - .github/workflows/test_canary.yml

jobs:     
  canary-test:
    name: Canary Region Tests
    uses: ./.github/workflows/test_sidecars.yml
    secrets: inherit
    with:
      locations: '["eastus2euap"]'

  canary-status:
    name: Canary Region Status
    uses: ./.github/workflows/status.yml
    secrets: inherit
    with:
      locations: '["eastus2euap"]'
