name: Simple Server

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/simple_server/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/simple_server/**
  merge_group:
    branches:
      - main

jobs:
  simple-server:
    name: Simple Server
    uses: ./.github/workflows/run_test.yml
    secrets: inherit
    with:
      test: simple_server
