name: Test Remote Image

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/remote_image/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/remote_image/**
  merge_group:
    branches:
      - main

jobs:
  remote-image:
    name: Remote Image
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: remote_image