name: Test Sidecar Images in East US 2 EUAP (Canary Region)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"
  pull_request:
    paths:
      - .github/workflows/test_canary.yml

jobs:     
  canary-test:
    name: Canary Region Tests
    uses: ./.github/workflows/test_sidecars.yml
    secrets: inherit
    with:
      locations: '["eastus2euap"]'

  canary-status:
    name: Canary Region Status
    uses: ./.github/workflows/status.yml
    secrets: inherit
    with:
      locations: '["eastus2euap"]'

  simple-server-16core:
    name: Simple Server 16 Cores
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '["eastus2euap"]'
      manifest-modifiers: "SIMPLE_SERVER_CORES=16;SIMPLE_SERVER_RAM=16"
          
  simple-server-32core:
    name: Simple Server 32 Cores
    uses: ./.github/workflows/test_example.yml
    secrets: inherit
    with:
      example-name: simple_server
      locations: '["eastus2euap"]'
      manifest-modifiers: "SIMPLE_SERVER_CORES=32;SIMPLE_SERVER_RAM=32"
