name: Uptime of Containers on West Europe

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  uptime-westeurope:
    uses: ./.github/workflows/uptime.yml
    secrets: inherit
    with:
      location: westeurope
