on:
  workflow_dispatch:

env:
  UPTIME_HRS: 48

jobs:
  check-current-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Check Current Containers
        run: |
          echo "Checking current containers"

  remove-old-container:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Old Container
        run: |
          echo "Removing old containers"

  prep-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Matrix Cell Name
        id: generate-name
        run: echo "name=$(echo simple_server-eastus2euap-allow_all.rego-uptime-${{ github.event.created_at }} | md5sum | sed 's/ //g' | sed 's/-//g')" >> $GITHUB_OUTPUT

      - name: Generate ARM Template
        run: python generate_arm_template.py \
          --name uptime-${{ github.event.created_at }} \
          --image-tag latest \
          --manifest-path tests/simple_server/manifest.json \
          --location eastus2euap \
          --security-policy $(cat tests/simple_server/security_policies/allow_all.rego | base64) \
          --out arm_template.json

      - name: Upload ARM Template Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.generate-name.outputs.name }}_arm_template
          path: arm_template.json

  deploy-new-container:
    uses: ./.github/workflows/deploy_container.yml
    needs: [check-current-containers, prep-deployment]
    secrets: inherit
    with:
      id: ${{ github.event.created_at }}
      test: simple_server
      location: eastus2euap
      security-policy: allow_all.rego
