name: Regional Uptime of Containers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  regional-uptime:
    strategy:
      matrix: 
        location: [eastus2euap, westeurope]
    uses: ./.github/workflows/_uptime.yml
    secrets: inherit
    with:
      location: ${{ matrix.location }}
